sudo: required

services:
  - docker

language: python

script:
  - python -m pytest -v 

after_success:
  - sh .travis/deploy_dockerhub.sh 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
